title: Environmental
icon: mdi:home-thermometer
path: env
type: horizontal-stack
cards:
- type: entities
  title: Environmental
  show_header_toggle: false
  entities:
    - entity: sensor.where_cooler
      name:
- type: sensor
  entity: sensor.local_temperature
  name: Local Temperature
  graph: line
- type: sensor
  entity: sensor.current_temperature
  name: Indoor Temperature
  graph: line
- type: sensor
  entity: sensor.luke_s_room_temperature
  name: Luke's Room Temperature
  graph: line
- type: sensor
  entity: sensor.hvac_duct_temperature
  name: HVAC Output
  graph: line
- type: sensor
  entity: sensor.porch_temperature
  name: Porch Temperature
  graph: line
