title: Temperatures
icon: mdi:shield-lock
path: security
cards:
 - type: entity-button
   name: Alarm System
   tap_action:
     action: call-service
     service: automation.turn_on
     service_data:
       entity_id: group.alarm_system
