title: Temperatures
icon: mdi:shield-lock
path: security
cards:
  - type: entities
    title: Alarm System
    show_header_toggle: false
    entities:
      - entity: group.alarm_system
  - type: entities
    title: Alarm Sensors
    show_header_toggle: false
    entities:
      - entity: binary_sensor.garage_man_door
      - entity: binary_sensor.garage_door
      - entity: binary_sensor.family_room_motion
      - entity: binary_sensor.luke_s_bedroom_door
      - entity: binary_sensor.tablet_cabinet
