title: Access Control
icon: mdi:shield-lock
path: security
cards:
  - type: entity-button
    entity: cover.garage_door
    icon: mdi:garage-variant
  - type: entities
    title: Alarm System
    show_header_toggle: false
    entities:
      - entity: group.alarm_system
      - type: divider
      - entity: automation.garage_man_door_alarm
      - entity: automation.living_room_motion_alarm
      - entity: automation.hallway_motion
      - entity: automation.luke_door_alarm
      - entity: automation.joel_emily_s_door_alarm
      - entity: automation.front_door_alarm
  - type: entities
    title: Motion Sensors
    show_header_toggle: false
    entities:
      - entity: binary_sensor.garage_motion
      - entity: binary_sensor.wyzesense_779d4464
      - entity: binary_sensor.wyzesense_7798e926
      - entity: binary_sensor.wyzesense_779d5d80
      - entity: binary_sensor.wyzesense_77a5e9bd
  - type: entities
    title: Door Sensors
    show_header_toggle: false
    entities:
      - entity: binary_sensor.garage_man_door
      - entity: binary_sensor.garage_door
      - entity: binary_sensor.garage_side_door
      - entity: binary_sensor.wyzesense_779be395
      - entity: binary_sensor.wyzesense_779c28a0
      - entity: binary_sensor.wyzesense_779c28b9
      - entity: binary_sensor.wyzesense_779be342
