title: Access Control
icon: mdi:shield-lock
path: security
cards:
  - type: entities
    title: Alarm System
    show_header_toggle: false
    entities:
      - entity: group.alarm_system
      - type: divider
      - entity: automation.garage_man_door_alarm
      - entity: automation.living_room_motion_alarm
  #   - entity: automation.luke_door_alarm
      - entity: automation.tablet_cabinet_alarm
  - type: entities
    title: Alarm Sensors
    show_header_toggle: false
    entities:
      - entity: binary_sensor.garage_man_door
      - entity: binary_sensor.garage_door
      - entity: binary_sensor.garage_motion
      - entity: binary_sensor.family_room_motion
      - entity: binary_sensor.tablet_cabinet
  - type: entity-button
    entity: cover.garage_door
    icon: mdi:garage-variant
