# - id: '1532816012846'
#   alias: Kitchen Lights Motion
#   trigger:
#   - entity_id: binary_sensor.wemo_motion
#     from: 'off'
#     platform: state
#     to: 'on'
#   condition:
#     condition: and
#        conditions:
#          - condition: state
#             entity_id: light.living_room
#             state: 'off'
#          - condition: time
#             after: '23:00:00'
#             before: '05:00:00'
#   action:
#   - data:
#       brightness: 128
#       entity_id: light.2be2ca
#       transition: 3
#     service: light.turn_on
#   - delay: '45'
#   - alias: ''
#     data:
#       entity_id: light.2be2ca
#       transition: 3
#     service: light.turn_off

# - id: '1545178911234'
#   alias: 'Update config if travis build is successful'
#   trigger:
#     platform: state
#     entity_id: sensor.department_g33k_hassio_config_state
#     #entity_id: sensor.departmentg33khassioconfig_last_build_state
#     from: 'started'
#     to: 'passed'
#   action:
#     - service: shell_command.github_pull
#     - service: homeassistant.restart

#- id: '1532018612846'
#  alias: Outdoor Lights Button Link On
#  trigger:
#  - entity_id: switch.22cdf9_3
#    from: 'off'
#    platform: state
#    to: 'on'
#  action:
#  - data:
#      entity_id: switch.outdoor_christmas_lights
#    service: switch.turn_on

#- id: '1532018612847'
#  alias: Outdoor Lights Button Link Off
#  trigger:
#  - entity_id: switch.22cdf9_3
#    from: 'on'
#    platform: state
#    to: 'off'
#  action:
#  - data:
#      entity_id: switch.outdoor_christmas_lights
#    service: switch.turn_off

#- id: '1532018712848'
#  alias: Tree Lights Button Link On
#  trigger:
#  - entity_id: switch.22cdf9_4
#    from: 'off'
#    platform: state
#    to: 'on'
#  action:
#  - data:
#      entity_id: switch.christmas_lights_2
#    service: switch.turn_on

#- id: '1532018712849'
#  alias: Tree Lights Button Link Off
#  trigger:
#  - entity_id: switch.22cdf9_4
#    from: 'on'
#    platform: state
#    to: 'off'
#  action:
#  - data:
#      entity_id: switch.christmas_lights_2
#    service: switch.turn_on

- id: '58888675309'
  alias: Porch Lights on at Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:05:00"
  action:
    service: switch.turn_on
    entity_id: switch.keypadlinc_on_off_22_cd_f9_main
- id: '58888675310'
  alias: Porch Lights off at 22:15
  trigger:
    platform: time
    at: "22:30:00"
  action:
    service: switch.turn_off
    entity_id: switch.keypadlinc_on_off_22_cd_f9_main
- id: '58888675311'
  alias: Entertainment Center off at 0430
  trigger:
    platform: time
    at: "04:00:00"
  action:
    service: switch.turn_off
    entity_id:  switch.entertainment_center

- id: '58888675312'
  alias: Entertainment Center on at 0600
  trigger:
    platform: time
    at: "06:00:00"
  action:
    service: switch.turn_on
    entity_id:  switch.entertainment_center
- id: '00004721002'
  alias: Garage Man Door Announcement
  trigger:
      platform: state
      entity_id: binary_sensor.garage_man_door
  action:
      service: tts.google_translate_say
      #entity_id: media_player.googlehomehub7838
      entity_id: media_player.googlehome7008
      data_template:
        message: "Garage Man Door"
        cache: false
- id: '00004721003'
  alias: Two Minute Warning Spiel
  trigger:
      platform: state
      entity_id: binary_sensor.garage_man_door
  action:
      service: tts.google_translate_say
      #entity_id: media_player.googlehomehub7838
      entity_id: media_player.whole_house_speakers
      data_template:
        message: "Attention!  This is your two Minute Warning!"
        cache: false

#Automations to handle the PIR sensor to control the Room light.
- alias: Luke's Room Motion Alarm
  id: '00004721004'
  trigger:
    platform: state
    entity_id: sensor.luke_s_room_motion
    to: 'ON'
  action:
    service: light.turn_on
    entity_id: light.monitor_leds
    service: tts.google_translate_say
    entity_id: media_player.whole_house_speakers
    data_template:
      message: "Motion Detected in Luke's Room"
      cache: false
- id: '00004711005'
  alias: Luke Night Light off at 1030
  trigger:
    platform: time
    at: "22:30:00"
  action:
    service: switch.turn_off
    entity_id:  switch.christmas_lights

- id: '00004711006'
  alias: Luke Night Light on at 1800
  trigger:
    platform: time
    at: "18:00:00"
  action:
    service: switch.turn_on
    entity_id:  switch.christmas_lights

- id: '00004711006'
  alias: Bedtime Reminder
  trigger:
    platform: time
    at: "00:41:00"
  condition:
    condition: state
    entity_id: light.monitor_leds
    state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.monitor_leds
      color_name: green
      brightness: 255
      flash: long

- id: '00004711007'
  alias: Office Lights Off
  trigger:
    platform: time
    at: "03:41:00"
  action:
  - service: light.turn_off
    data:
      - entity_id: light.monitor_leds
        entity_id: light.lamplinc_dimmer_3a_b1_e7
        transition: 45
