- id: '1532815413356'
  alias: A/C On - Indicator
  trigger:
  - entity_id: climate.thermostat
    from: idle
    platform: state
    to: cool
  condition: []
  action:
  - data:
      brightness: 175
      effect: solid
      entity_id: light.portable_leds
      rgb_color:
      - 0
      - 200
      - 255
    service: light.turn_on
  - delay: '5'
  - alias: ''
    data:
      entity_id: light.portable_leds
      transition: 1
    service: homeassistant.turn_off
- id: '1532816012846'
  alias: Kitchen Lights Motion
  trigger:
  - entity_id: binary_sensor.wemo_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.2be2ca
    state: 'off'
# - condition: time
#        after: '23:00:00'
#        before: '05:00:00'
  action:
  - data:
      brightness: 128
      entity_id: light.2be2ca
      transition: 3
    service: light.turn_on
  - delay: '45'
  - alias: ''
    data:
      entity_id: light.2be2ca
      transition: 3
    service: light.turn_off
- id: '1535862775948'
  alias: Yellow Light Warning
  trigger:
  - at: '22:15'
    platform: time
  condition: []
  action:
  - data:
      brightness: 255
      effect: solid
      entity_id: light.portable_leds
      rgb_color:
      - 255
      - 255
      - 0
      transition: 3
    service: light.turn_on
- id: '1535863112483'
  alias: Red Light Warning
  trigger:
  - at: '22:25'
    platform: time
  condition: []
  action:
  - data:
      brightness: 255
      effect: solid
      entity_id: light.monitor_leds
      rgb_color:
      - 255
      - 0
      - 0
      transition: 3
    service: light.turn_on
  - delay: '600'
  - data:
      entity_id: light.monitor_leds
      transition: 3
    service: light.turn_off
- id: '1539323477333'
  alias: Lights Out
  trigger:
    - entity_id: input_boolean:lights_out
      from: 'off'
      platform: state
      to: 'on'
    condition: []
    action:
    - service: input_boolean:turn_off
    - data: {entity_id: light.3ab1e7}
      service: light.turn_off
    - data: {entity_ id:light.monitor_leds}
      service: light.turn_off
