- platform: ping
  host: 192.168.200.254
  name: HomeRouter
- platform: ping
  host: 8.8.8.8
  name: GoogleDNS
- platform: ping
  host: 1.1.1.1
  name: CloudFlareDNS
- platform: ping
  host: 192.168.200.105
  name: FamilyRoomTV
#- platform: rpi_gpio
#  ports:
#    23: Garage Man Door
#    24: Garage Door
- platform: threshold
  entity_id: sensor.softener_salt
  upper: 60
  name: Softener Salt OK
- platform: threshold
  entity_id: sensor.fridge_door_light
  name: Fridge Door Binary
  upper: 100

- platform: mqtt
  state_topic: "lab/red-button/state"
  name: "Red Button"
  qos: 0

- platform: mqtt
  state_topic: "lab/green-button/state"
  name: "Green Button"
  qos: 0

- platform: mqtt
  state_topic: "lrs/door"
  name: "Luke's Bedroom Door"
  qos: 0
  device_class: door
