- platform: ping
  host: 192.168.200.254
  name: HomeRouter

- platform: ping
  host: 8.8.8.8
  name: GoogleDNS

- platform: ping
  host: 1.1.1.1
  name: CloudFlareDNS

- platform: ping
  host: 192.168.200.105
  name: FamilyRoomTV

- platform: threshold
  entity_id: sensor.softener_salt
  upper: 60
  name: Softener Salt OK

- platform: threshold
  entity_id: sensor.fridge_door_light
  name: Fridge Door Binary
  upper: 100

- platform: mqtt
  state_topic: "lab/red-button/state"
  name: "Red Button"
  qos: 1
  payload_on: "1"
  payload_off: "0"

- platform: mqtt
  state_topic: "lrs/door"
  name: "Luke's Bedroom Door"
  qos: 0
  device_class: door

- platform: mqtt
  state_topic: "garage/man-door/state"
  name: "Garage Man Door"
  qos: 1
  device_class: door
  payload_on: "1"
  payload_off: "0"

- platform: mqtt
  state_topic: "lrs/motion"
  name: "Luke's Room Motion"
  device_class: motion
  qos: 0

- platform: mqtt
  state_topic: "garage/garage-door/state"
  name: "Garage Door"
  device_class: garage_door
  qos: 1
  payload_on: "1"
  payload_off: "0"

  - platform: mqtt
    state_topic: "lab/green-button/state"
    name: "Green Button"
    qos: 0
    payload_on: "1"
    payload_off: "0"
