- platform: mqtt
  schema: json
  name: "Monitor LEDs"
  state_topic: "deptg33k/MonLED"
  command_topic: "deptg33k/MonLED/set"
  effect: true
  effect_list:

    - candy cane
    - confetti
    - cyclon rainbow
    - dots
    - fire
    - lightning
    - noise
    - police all
    - police one
    - rainbow
    - rainbow with glitter
    - ripple
    - solid
    - twinkle
  brightness: true
  rgb: true
  optimistic: false
  qos: 0
- platform: mqtt
  schema: json
  name: "Monitor LEDs"
  state_topic: "lab/MonLED"
  command_topic: "deptg33k/MonLED/set"
  effect: true
  effect_list:

    - candy cane
    - confetti
    - cyclon rainbow
    - dots
    - fire
    - lightning
    - noise
    - police all
    - police one
    - rainbow
    - rainbow with glitter
    - ripple
    - solid
    - twinkle
  brightness: true
  rgb: true
  optimistic: false
  qos: 0

- platform: mqtt
  schema: template
  name: "Luke Sensor Light"
  command_topic: "lrs/cmd"
  state_topic: "/lrs/led"
  command_off_template: 'Neopixel,1,0,0,0'
  command_on_template: 'Neopixel,1,{{ red|d }},{{ green|d }},{{ blue|d }}'
  red_template: "{{ value.split(',')[2].split(',')[0] }}"
  green_template: "{{ value.split(',')[2].split(',')[1] }}"
  blue_template: "{{ value.split(',')[2].split(',')[2] }}"
