- platform: yr

- platform: onewire

- platform: openweathermap
  api_key: 612d4b28cc2c7d7b40030569b3adf10e
  monitored_conditions:
      - temperature
      - wind_speed
      - humidity

- platform: darksky
  api_key: e2f39ae845f15070a7aa304dc9a1c943
  monitored_conditions:
      - precip_accumulation
      - precip_type
      - temperature

- platform: mqtt
  state_topic: "multi/probe_temp"
  name: "Shed Temperature"
  icon: mdi:thermometer
  unit_of_measurement: "°F"
  qos: 0

#- platform: mqtt
#  state_topic: "multi/wetness"
#  name: "Kitchen Water Sensor"
#  icon: mdi:water
#  unit_of_measurement: "how dry"
#  qos: 0

- platform: mqtt
  state_topic: "dist/salt_tank"
  name: "Softener Salt"
  icon: mdi:flask-outline
  unit_of_measurement: "cm"
  qos: 0

- platform: mqtt
  state_topic: "multi/humidity"
  name: "Shed Humidity"
  icon: mdi:water-percent
  unit_of_measurement: "%"
  qos: 0

- platform: mqtt
  state_topic: "multi/ambient_temp"
  name: "Shed Ambient Temperature"
  icon: mdi:oil-temperature
  unit_of_measurement: "°F"
  qos: 0

- platform: mqtt
  state_topic: "masterbath/humidity"
  name: "Bathroom Humidity"
  icon: mdi:water-percent
  unit_of_measurement: "%"
  qos: 0

- platform: mqtt
  state_topic: "masaterbath/temp"
  name: "Bathroom Ambient Temperature"
  icon: mdi:oil-temperature
  unit_of_measurement: "°F"
  qos: 0

- platform: min_max
  name: Local Temperature
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.dark_sky_temperature
    - sensor.owm_temperature
    - sensor.280315043b90ff_temperature

- platform: travisci
  api_key: !secret travisapi_key
  repository: hassio-config
  monitored_conditions:
    - state
- platform: airvisual
  api_key: !secret airvisual_key
  monitored_conditions:
    - us
  city: Modesto
  state: California
  country: USA

- platform: time_date
  display_options:
    - 'time'

#- platform: mqtt
#  state_topic: "home-assistant/kitchen/temperature"
#  name: "Kitchen Temperature"
#  unit_of_measurement: "°F"

- platform: mqtt
  state_topic: "lukesroom/ldr"
  name: "Luke's Room Light Level"
  icon: mdi:theme-light-dark
  unit_of_measurement: "LUX"
  qos: 0

- platform: mqtt
  state_topic: "lukesroom/motion"
  name: "Luke's Room Motion"
  qos: 0

- platform: mqtt
  state_topic: "lukesroom/heatindex"
  name: "Luke's Room Temperature"
  icon: mdi:temperature-fahrenheit
  unit_of_measurement: "°F"
  qos: 0

- platform: mqtt
  state_topic: "lukesroom/humidity"
  name: "Luke's Room Humidity"
  icon: mdi:water-percent
  unit_of_measurement: "%"
  qos: 0

- platform: mqtt
  state_topic: "testsensor/in/rssi"
  name: "Wireless Sensor RSSI"
  unit_of_measurement: "db"
  qos: 0

- platform: mqtt
  state_topic: "kitchenplants/soilmoisture"
  name: "Kitchen plant soil dryness"
  unit_of_measurement: "%"
  value_template: '{{ value | multiply(0.1) | float }}'
  qos: 0
#group:
#  sensor_node_1_card:
#    name: Sensor Node 1
#    entities:
#      - sensor.sn1_temperature
#      - sensor.sn1_humidity
#      - sensor.sn1_ldr
#      - sensor.sn1_pir

#

# - platform: template
#   sensors:
#     switch.outdoor_christmas_lights_amps:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Current"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["current_a"] | float }}'
#       unit_of_measurement: 'A'
#     switch.outdoor_christmas_lights_watts:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Current Consumption"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["current_power_w"] | float }}'
#       unit_of_measurement: 'W'
#     switch.outdoor_christmas_lights_total_kwh:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Total Consumption"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["total_energy_kwh"] | float }}'
#       unit_of_measurement: 'kWh'
#     switch.outdoor_christmas_lights_volts:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Voltage"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["voltage"] | float }}'
#       unit_of_measurement: 'V'
#     switch.outdoor_christmas_lights_today_kwh:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Today's Consuption"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["today_energy_kwh"] | float }}'
#       unit_of_measurement: 'kWh'
