- platform: yr

- platform: openweathermap
  api_key: 612d4b28cc2c7d7b40030569b3adf10e
  monitored_conditions:
      - temperature
      - wind_speed
      - humidity

- platform: darksky
  api_key: e2f39ae845f15070a7aa304dc9a1c943
  monitored_conditions:
      - precip_accumulation
      - precip_type
      - temperature

- platform: mqtt
  state_topic: "garage/rack/temperature"
  name: "Server Rack Temperature"
  icon: mdi:thermometer
  unit_of_measurement: "°F"
  qos: 0

#- platform: mqtt
#  state_topic: "multi/wetness"
#  name: "Kitchen Water Sensor"
#  icon: mdi:water
#  unit_of_measurement: "how dry"
#  qos: 0

- platform: mqtt
  state_topic: "garage/salt/level"
  name: "Softener Salt"
  icon: mdi:flask-outline
  unit_of_measurement: "in"
  qos: 0

- platform: mqtt
  state_topic: "garage/porch/temperature"
  name: "Porch Temperature"
  icon: mdi:thermometer
  unit_of_measurement: "°F"
  qos: 0

- platform: mqtt
  state_topic: "fridge/Light/Light"
  name: "Fridge Door Light"
  icon: mdi:fridge-bottom
  unit_of_measurement: ""
  qos: 0

- platform: mqtt
  state_topic: "fridge/Environmental/Humidity"
  name: "Fridge Humidity"
  icon: mdi:fridge-outline
  unit_of_measurement: "%"
  qos: 0

- platform: mqtt
  state_topic: "fridge/Environmental/Temperature"
  name: "Fridge Temperature"
  icon: mdi:fridge-outline
  unit_of_measurement: "°F"
  qos: 0

- platform: mqtt
  state_topic: "fridge/Probe/Temperature"
  name: "Fridge Probe Temperature"
  icon: mdi:fridge
  unit_of_measurement: "°F"
  qos: 0

- platform: min_max
  name: Local Temperature
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.dark_sky_temperature
    - sensor.owm_temperature
    - sensor.280315043b90ff_temperature

- platform: travisci
  api_key: !secret travisapi_key
  repository: hassio-config
  monitored_conditions:
    - state
- platform: airvisual
  api_key: !secret airvisual_key
  monitored_conditions:
    - us
  city: Modesto
  state: California
  country: USA

- platform: time_date
  display_options:
    - 'time'

#- platform: mqtt
#  state_topic: "home-assistant/kitchen/temperature"
#  name: "Kitchen Temperature"
#  unit_of_measurement: "°F"

- platform: mqtt
  state_topic: "lrs/Light"
  name: "Luke's Room Light Level"
  icon: mdi:theme-light-dark
  unit_of_measurement: "LUX"
  qos: 0

- platform: mqtt
  state_topic: "lrs/motion"
  name: "Luke's Room Motion"
  qos: 0

- platform: mqtt
  state_topic: "lrs/temperature"
  name: "Luke's Room Temperature"
  icon: mdi:temperature-fahrenheit
  unit_of_measurement: "°F"
  qos: 0

- platform: mqtt
  state_topic: "lrs/humidity"
  name: "Luke's Room Humidity"
  icon: mdi:water-percent
  unit_of_measurement: "%"
  qos: 0
#
- platform: mqtt
  state_topic: "garage/hvac/temperature"
  name: "HVAC Duct Temperature"
  unit_of_measurement: "°F"
  icon: mdi:air-conditioner
  qos: 0

- platform: mqtt
  state_topic: "kitchenplants/soilmoisture"
  name: "Kitchen plant soil dryness"
  unit_of_measurement: "%"
  value_template: '{{ value | multiply(0.1) | float }}'
  qos: 0

- platform: mqtt
  state_topic: "sickkid/temp"
  name: "Sick Kid Temperature"
  icon: mdi:thermometer-alert
  unit_of_measurement: "°F"
  qos: 0

- platform: mqtt
  state_topic: "sickkid/meds"
  name: "Sick Kid Meds"
  icon: mdi:pill
  unit_of_measurement: "dose"
  qos: 0

- platform: template
  sensors:
    current_temperature:
      friendly_name: Indoor Temperature
      value_template: "{{ state_attr('climate.THERMOSTAT', 'current_temperature') }}"
      unit_of_measurement: "°F"

- platform: template
  sensors:
    outside_vs_inside_temp:
    value_template: "{% if states.sensor.local_temperature.state < states.sensor.current_temperature.state %}Run Fan{% else %}Run HVAC{%endif %}"
    friendly_name: "Indoor Vs Outdoor"

#group:
#  sensor_node_1_card:
#    name: Sensor Node 1
#    entities:
#      - sensor.sn1_temperature
#      - sensor.sn1_humidity
#      - sensor.sn1_ldr
#      - sensor.sn1_pir

#

# - platform: template
#   sensors:
#     switch.outdoor_christmas_lights_amps:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Current"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["current_a"] | float }}'
#       unit_of_measurement: 'A'
#     switch.outdoor_christmas_lights_watts:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Current Consumption"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["current_power_w"] | float }}'
#       unit_of_measurement: 'W'
#     switch.outdoor_christmas_lights_total_kwh:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Total Consumption"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["total_energy_kwh"] | float }}'
#       unit_of_measurement: 'kWh'
#     switch.outdoor_christmas_lights_volts:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Voltage"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["voltage"] | float }}'
#       unit_of_measurement: 'V'
#     switch.outdoor_christmas_lights_today_kwh:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Today's Consuption"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["today_energy_kwh"] | float }}'
#       unit_of_measurement: 'kWh'
- platform: mqtt
  state_topic: "acura/system/rssi"
  name: "Acura Sensor RSSI"
  unit_of_measurement: "dB"
  icon: mdi:signal-cellular-2
  qos: 0

- platform: mqtt
  state_topic: "acura/system/uptime"
  name: "Acura Sensor Uptime"
  unit_of_measurement: "min"
  icon: mdi:av-timer
  qos: 0

- platform: mqtt
  state_topic: "acura/system/vcc"
  name: "Acura Sensor Uptime"
  unit_of_measurement: "volts"
  icon: mdi:battery-50
  qos: 0

- platform: mqtt
  state_topic: "acura/network/a"
  name: "1st Octet"
  unit_of_measurement: ""
  icon: mdi:ip-nework
  qos: 0

- platform: mqtt
  state_topic: "acura/network/b"
  name: "2nd Octet"
  unit_of_measurement: ""
  icon: mdi:ip-nework
  qos: 0

- platform: mqtt
  state_topic: "acura/network/c"
  name: "3rd Octet"
  unit_of_measurement: ""
  icon: mdi:ip-nework
  qos: 0

- platform: mqtt
  state_topic: "acura/network/d"
  name: "4th Octet"
  unit_of_measurement: ""
  icon: mdi:ip-nework
  qos: 0
