- platform: yr
- platform: onewire

  - platform: darksky
    api_key: e2f39ae845f15070a7aa304dc9a1c943
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - precip_accumulation
      - precip_intensity
      - wind_speed
      - humidity
