- platform: yr

- platform: onewire

- platform: openweathermap
  api_key: 612d4b28cc2c7d7b40030569b3adf10e
  monitored_conditions:
      - temperature
      - wind_speed
      - humidity
      - rain

- platform: darksky
  api_key: e2f39ae845f15070a7aa304dc9a1c943
  monitored_conditions:
      - precip_accumulation
      - precip_type
      - temperature

- platform: mqtt
  state_topic: "temp/wireless_1"
  name: "Wireless Thermometer"
  icon: mdi:temperature-fahrenheit
  unit_of_measurement: "°F"
  qos: 0

- platform: min_max
  name: Local Temperature
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.dark_sky_temperature
    - sensor.owm_temperature
    - sensor.280315043b90ff_temperature

- platform: travisci
  api_key: !secret travisapi_key
  repository: hassio-config
  monitored_conditions:
    - state
- platform: airvisual
  api_key: !secret airvisual_key
  monitored_conditions:
    - us
  city: Modesto
  state: California
  country: USA

- platform: time_date
  display_options:
    - 'time'

# - platform: template
#   sensors:
#     my_tp_switch_amps:
#       friendly_name_template: "{{ states.switch.my_tp_switch.name}} Current"
#       value_template: '{{ states.switch.my_tp_switch.attributes["current_a"] | float }}'
#       unit_of_measurement: 'A'
#     my_tp_switch_watts:
#       friendly_name_template: "{{ states.switch.my_tp_switch.name}} Current Consumption"
#       value_template: '{{ states.switch.my_tp_switch.attributes["current_power_w"] | float }}'
#       unit_of_measurement: 'W'
#     my_tp_switch_total_kwh:
#       friendly_name_template: "{{ states.switch.my_tp_switch.name}} Total Consumption"
#       value_template: '{{ states.switch.my_tp_switch.attributes["total_energy_kwh"] | float }}'
#       unit_of_measurement: 'kWh'
#     my_tp_switch_volts:
#       friendly_name_template: "{{ states.switch.my_tp_switch.name}} Voltage"
#       value_template: '{{ states.switch.my_tp_switch.attributes["voltage"] | float }}'
#       unit_of_measurement: 'V'
#     my_tp_switch_today_kwh:
#       friendly_name_template: "{{ states.switch.my_tp_switch.name}} Today's Consuption"
#       value_template: '{{ states.switch.my_tp_switch.attributes["today_energy_kwh"] | float }}'
#       unit_of_measurement: 'kWh'
