- platform: yr

- platform: onewire

- platform: openweathermap
  api_key: 612d4b28cc2c7d7b40030569b3adf10e
  monitored_conditions:
      - temperature
      - wind_speed
      - humidity

- platform: darksky
  api_key: e2f39ae845f15070a7aa304dc9a1c943
  monitored_conditions:
      - precip_accumulation
      - precip_type
      - temperature

- platform: mqtt
  state_topic: "temp/wireless_1"
  name: "Wireless Thermometer"
  icon: mdi:temperature-fahrenheit
  unit_of_measurement: "°F"
  qos: 0

- platform: mqtt
  state_topic: "water/wetness"
  name: "Kitchen Water Sensor"
  icon: mdi:water
  unit_of_measurement: "% wet"
  value_template: '{{ ((value_json.ldr|float-1023)/1023*100)|round(0) }}'
  qos: 0

- platform: mqtt
  state_topic: "dist/salt_tank"
  name: "Softener Salt"
  icon: mdi:flask-outline
  unit_of_measurement: "cm"
  qos: 0

- platform: mqtt
  state_topic: "temp/kitchen"
  name: "Kitchen Temperature"
  unit_of_measurement: "°F"

- platform: min_max
  name: Local Temperature
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.dark_sky_temperature
    - sensor.owm_temperature
    - sensor.280315043b90ff_temperature

- platform: travisci
  api_key: !secret travisapi_key
  repository: hassio-config
  monitored_conditions:
    - state
- platform: airvisual
  api_key: !secret airvisual_key
  monitored_conditions:
    - us
  city: Modesto
  state: California
  country: USA

- platform: time_date
  display_options:
    - 'time'
#
# - platform: template
#   sensors:
#     switch.outdoor_christmas_lights_amps:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Current"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["current_a"] | float }}'
#       unit_of_measurement: 'A'
#     switch.outdoor_christmas_lights_watts:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Current Consumption"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["current_power_w"] | float }}'
#       unit_of_measurement: 'W'
#     switch.outdoor_christmas_lights_total_kwh:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Total Consumption"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["total_energy_kwh"] | float }}'
#       unit_of_measurement: 'kWh'
#     switch.outdoor_christmas_lights_volts:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Voltage"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["voltage"] | float }}'
#       unit_of_measurement: 'V'
#     switch.outdoor_christmas_lights_today_kwh:
#       friendly_name_template: "{{ states.switch.outdoor_christmas_lights.name}} Today's Consuption"
#       value_template: '{{ states.switch.outdoor_christmas_lights.attributes["today_energy_kwh"] | float }}'
#       unit_of_measurement: 'kWh'
