- platform: yr

- platform: onewire

- platform: openweathermap
  api_key: 612d4b28cc2c7d7b40030569b3adf10e
  monitored_conditions:
      - temperature
      - wind_speed
      - humidity
      - rain

- platform: darksky
  api_key: e2f39ae845f15070a7aa304dc9a1c943
  monitored_conditions:
      - nearest_storm_distance
      - precip_accumulation
      - precip_type
      - temperature
      - wind_speed

- platform: mqtt
  state_topic: "temp/wireless_1"
  name: "Wireless Thermometer"
  icon: mdi:temperature-fahrenheit
  unit_of_measurement: "°F"
  qos: 0

- platform: min_max
  name: Local Temperature
  round_digits: 1
  type: mean
  entity_ids:
    - sensor.dark_sky_temperature
    - sensor.owm_temperature
    - sensor.280315043b90ff_temperature

- platBREAKSOMETHING
