  #- platform: rpi_gpio
  #  ports:
  #    18: Sprinkler Rain Mode
#
- platform: mqtt
  name: "Garage Lights"
  command_topic: "lrs/cmd"
  state_topic: "lrs/garage_lights"
  payload_on: "pulse,16,1,75"
  payload_off: "pulse,16,1,75"
  state_on: 1
  state_off: 0
