  #- platform: rpi_gpio
  #  ports:
  #    18: Sprinkler Rain Mode
#
- platform: mqtt
  name: "Garage Lights"
  command_topic: "lrs/cmd"
  state_topic: "lrs/garage_lights"
  payload_on: "pulse,16,1,75"
  payload_off: "pulse,16,1,75"
  state_on: 1
  state_off: 0

- platform: wake_on_lan
  mac: B0:7B:25:02:82:8A
  name: "Turn on Office Computer"
  host: 192.168.200.239

- platform: template
  switches:
    my_computer:
      friendly_name: "Office Computer"
      value_template: "{{ is_state('binary_sensor.office_computer_connected', 'on') }}"
      turn_on:
        service: script.office_computer_wake
      turn_off:
        service: script.office_computer_hibernate
      icon_template: mdi:laptop
    airquality_mode:
      friendly_name: Air Quality Mode
      value_template: "{{ is_state_attr('climate.thermostat', 'fan_mode', 'on') }}"
      turn_on:
        service: climate.set_fan_mode
        data:
          fan_mode: on
          entity_id: climate.thermostat
      turn_off:
        service: climate.set_fan_mode
        data:
          fan_mode: auto
          entity_id: climate.thermostat
      icon_template: hass:radioactive
