  #- platform: rpi_gpio
  #  ports:
  #    18: Sprinkler Rain Mode
#
- platform: mqtt
  name: "Garage Lights"
  command_topic: "lrs/cmd"
  state_topic: "lrs/garage_lights"
  payload_on: "pulse,16,1,75"
  payload_off: "pulse,16,1,75"
  state_on: 1
  state_off: 0

- platform: wake_on_lan
  mac: 00:50:B6:BD:6B:C1
  name: "Turn on Office Computer"
  host: 192.168.200.226

- platform: template
  switches:
    my_computer:
      friendly_name: "Office Computer"
      value_template: "{{ is_state('binary_sensor.office_computer_connected', 'on') }}"
      turn_on:
        service: script.office_computer_wake
      turn_off:
        service: script.office_computer_hibernate
      icon_template: mdi:laptop
    AQImode:
      value_template: "{{ is_state('climate.thermostat.fan_mode', 'on') }}"
      turn_on:
        service: climate.set_fan_mode
        data: on
        entity_id: switch.aqimode_on
      turn_off:
        service: climate.set_fan_mode
        data: auto
        entity_id: switch.aqimode_off
      icon_template: hass:biohazard
