title: Home
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
  - title: Lights
    icon: mdi:lightbulb-on
    path: lights
    cards:
    - type: entities
      title: Lighting Control
      show_header_toggle: false
      entities:
        - type: section
          label: Outdoor
        - entity: switch.22cdf9_2
          name: Porch Lights
          #type: custom:slider-entity-row
          toggle: true
        - entity: switch.30cd2c_2
          name: Sideyard Lights
        - type: section
          label: Front Area
        - entity: light.16266e
          name: Living Room Lights
          toggle: true
        - entity: light.2be2ca
          label: Kitchen Lights
        - type: section
          label: Gallway
        - entity: light.167ccf
          label: Hallway Lights
        - entity: light.1bbfe2
          label: Kid's Bathroom lights
        - type: section
          label: Master Bedroom
        - entity: light.3ab32f_2
          label: Nightstand Light
        - type: section
          label: Office
        - entity: light.3ab1e7
          label: Desk Lamp
        - entity: light.monitor_leds
          label: Monitor Light
  - title: Sensors
    icon: mdi:gauge
    path: sensors
  - type: vertical-stack
    cards:
      - type: sensor
        entity: sensor.luke_s_room_light_level
        name: Luke's Room Light Level
        graph: line
      - type: sensor
        entity: sensor.kitchen_water_sensor
        name: Kitchen Water Sensor
        graph: line
      - type: sensor
        entity: sensor.kitchen_temperature
        name: Kitchen Sink Water Temperature
        graph: line
      - type: sensor
        entity: sensor.softener_salt
        name: Water Softener Salt Level
        graph: line
      - type: sensor
        entity: binary_sensor.wemo_motion |||||
        name: Family Room Motion
      - type: sensor
        entity: binary_sensor.garage_door |||||
        name: Garage Overhead Door
      - type: sensor
        entity: binary_sensor.garage_man_door |||||
        name: Garage Man Door
