title: Home
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
#background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
#  - !include lovelace/00_home_view.yaml
#  - !include lovelace/20_lights_view.yaml

cards:
  - type: vertical-stack
    cards:
    # - type: custom:compact-custom-header
    #   voice: false
    #   clock: "options"
    #   clock_format: 24
    - type: horizontal-stack
      cards:
      #  - type: picture
      #    image: /local/lovelace_ui/bed.jpg
      #    tap_action:
      #      action: none
      #    hold_action:
      #      action: call-service
      #      service: script.goodnight
      #  - type: picture
      #    image: /local/lovelace_ui/morning_coffee_square.jpg
      #    tap_action:
      #      action: none
      #    hold_action:
      #      action: call-service
      #      service: scene.turn_on
      #      service_data:
      #        entity_id: scene.morning_lights
      #  - type: picture
      #    image: /local/lovelace_ui/movie_square.jpg
      #    tap_action:
      #      action: none
      #    hold_action:
      #      action: call-service
      #      service: scene.turn_on
      #      service_data:
      #        entity_id: scene.movie_time

    - type: entities
      title: Lighting Control
      show_header_toggle: false
      entities:
        - type: section
          label: Outdoor
        - entity: switch.22cdf9_2
          name: Porch Lights
          type: custom:slider-entity-row
          toggle: true
        - entity: switch.30cd2c_2
          name: Sideyard Lights

        - type: section
          label: Front House
        - entity: light.16266e
          name: Living Room Lights
          toggle: true
          type: custom:slider-entity-row
