title: Home
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

views:
  - !include /config/lovelace/dexter.yaml
  - !include /config/lovelace/ui-environmentals.yaml
  - !include /config/lovelace/ui-lights.yaml
  - !include /config/lovelace/ui-sensors.yaml
  - !include /config/lovelace/ui-health.yaml
  - !include /config/lovelace/ui-garage.yaml
  - !include /config/lovelace/ui-temperatures.yaml
