title: Home
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

views:
  - !include /config/lovelace/dexter.yaml
  - title: Lights
    icon: mdi:lightbulb-on
    path: lights
    cards:
    - type: entities
      title: Lighting Control
      show_header_toggle: false
      entities:
        - type: section
          label: Outdoor
        - entity: switch.22cdf9_2
          name: Porch Lights
          #type: custom:slider-entity-row
          toggle: true
        - entity: switch.30cd2c_2
          name: Sideyard Lights
        - type: section
          label: Front Area
        - entity: light.16266e
          name: Living Room Lights
          toggle: true
        - entity: light.2be2ca
          label: Kitchen Lights
        - type: section
          label: Hallway
        - entity: light.167ccf
          label: Hallway Lights
        - entity: light.1bbfe2
          label: Kid's Bathroom lights
        - type: section
          label: Master Bedroom
        - entity: light.3ab32f_2
          label: Nightstand Light
        - type: section
          label: Office
        - entity: light.3ab1e7
          label: Desk Lamp
        - entity: light.monitor_leds
          label: Monitor Light
  - title: Sensors
    icon: mdi:gauge
    path: sensors
    cards:
      - type: sensor
        entity: sensor.luke_s_room_light_level
        name: Luke's Room Light Level
        graph: line
      - type: sensor
        entity: sensor.kitchen_plant_soil_dryness
        name: Kitchen Plant Soil Dryness
        graph: line
      - type: sensor
        entity: sensor.softener_salt
        name: Water Softener Salt Level
        graph: line
  -  title: Garage
     icon: mdi:garage
     path: garage
     cards:
       - type: picture-glance
         title: Front Door
         entities:
           - binary_sensor.ring_front_door_motion
         camera_image: camera.front_door
  -  title: Temperatures
     icon: mdi:thermometer-lines
     path: thermo
     cards:
       - type: sensor
         name: Indoor Temperature
         entity: climate.thermostat.current_temperature
       - type: sensor
         name: HVAC Duct Temperature
         entity: sensor.28_0215030ffaff_temperature
       - type: sensor
         name: Rack Temperature
         entity: sensor.28_0315050445ff_temperature
       - type: sensor
         name: Front Temperature
         entity: sensor.28_0315050445ff_temperature
       - type: sensor
         name: Outdoor Temperature
         entity: sensor.local_temperature
         #
