title: My Awesome Home
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
    # View tab title.
  - title: Second view
    cards:
      - id: peoplehome # Every card needs an ID, if you don't specify one, it is added automatically.
        type: entity-filter
        entities:
          - device_tracker.samsungsmg950u
          - device_tracker.departmentg33k
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home  # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - light.kitchen
          - switch.ac
          - entity: light.living_room
            # Override the name to use
            name: LR Lights

        # The markdown card will render markdown text.
#     - type: custom:useful-markdown-card
#       padding: 0 15%
#       fontSize: 200px
       #title: Time
#       content: >

         [[ sensor.time.state ]]
  - icon: mdi:deskphone
    title: Wall Panel
    id: wall_panel
    cards:
      - type: glance
        title: Wall Panel
        entities:
          - entity: light.2be2ca
            name: Kitchen
            tap_action: toggle
          - entity: light.167ccf
            name: Hall
            tap_action: toggle
          - entity: light.16266e
            name: Family Room
            tap_action: toggle
          - entity: light.3ab1e7
            name: Desk Lamp
            icon: mdi:desk-lamp
            tap_action: toggle
          - entity: light.1bbfe2
            name: Bathroom
            icon: mdi:toilet
            tap_action: toggle
          - entity: binary_sensor.garage_door
            name: Garage Door
          - entity: sensor.local_temperature
            name: Outdoor
      - type: entity-button
        entity: light.3ab32f_2
        name: Nightstand
        icon: mdi:lamp
