title: Home
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
  - title: Lights
    icon: mdi:lightbulb-on
    path: lights
    cards:
    - type: entities
      title: Lighting Control
      show_header_toggle: false
      entities:
        - type: section
          label: Outdoor
        - entity: switch.22cdf9_2
          name: Porch Lights
          #type: custom:slider-entity-row
          toggle: true
        - entity: switch.30cd2c_2
          name: Sideyard Lights
        - type: section
          label: Front House
        - entity: light.16266e
          name: Living Room Lights
          toggle: true
          #type: custom:slider-entity-row
