title: My Awesome Home
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
    # View tab title.
  - title: Example
    # Unique id for direct access /lovelace/${id}. If you don't specify one, it is added automatically.
    id: example
    # Optional background (overwrites the global background).
    background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - id: peoplehome # Every card needs an ID, if you don't specify one, it is added automatically.
        type: entity-filter
        entities:
          - device_tracker.samsungsmg950u
          - device_tracker.departmentg33k
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home

        # The picture entity card will represent an entity with a picture
      - type: picture-entity
        image: https://www.home-assistant.io/images/default-social.png
        entity: light.bed_light

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Second view
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - light.kitchen
          - switch.ac
          - entity: light.living_room
            # Override the name to use
            name: LR Lights

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
  - icon: mdi:deskphone
    title: Wall Panel
    id: wall_panel
    cards:
      - type: glance
        title: Wall Panel
        entities:
          - entity: light.30cd2c
            name: Side Yard Light
          - entity: light.3ab32f
            name: Office Light
          - entity: light.3ab32f_2
            name: Office overhead light
          - entity: light.2be2ca
            name: Kitchen Lights
          - entity: light.167ccf
            name: Hall Lights
          - entity: light.16266e
            name: Living Room Lights
          - entity: switch.22cdf9
            name: Porch Lights
          - entity: light.1bc095
            name: Hall Light Remote
          - entity: light.3ab1e7
            name: Desk Lamp
            icon: mdi:desk-lamp
          - entity: light.1bbfe2
            name: Front Bathroom
            icon: mdi:toilet
