- alias: Zone 1
  id: 'sprinkler-zone-1'
  initial_state: true
  trigger:
    platform: time
    at: "06:45:00"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.sprinkler-z1
