- alias: Zone 1
  id: 'z1_a1'
  initial_state: false
  trigger:
    platform: state
    entity_id: switch.keypadlinc_dimmer_16_7c_cf_button_g
    to: 'off'
  action:
    service: tts.google_translate_say
    entity_id: media_player.office_speaker
    data_template:
      message: "Button G turned off"
      cache: false
