- alias:  Start WHF Sleep Timer
  id: 'wfh_sleep_start'
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.whfan_sleep_timer
    to: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.whfan_sleep_timer
    - service: timer.start
      data:
        entity_id: timer.whf_sleep

- alias: Turn off Fan
  id: 'turn_off_fan'
  initial_state: true
  trigger:
    platform: event
    entity_type: timer.finished
    event_data:
      entity_id: timer.wfh_sleep
  #condition:
  #  - condition: time
  action:
    - service: switch.turn_off
      data:
        entity_id: switchlinc_relay_dual_band_30_cd_2c


#- alias: Turn off WHFan
#  id: 'turn_off_whole_house_fan'
#  initial_state: "on"
#  trigger:
#    - platform: event
#      event_type: timer.finished
#      event_data:
#        entity_id: timer.whfsleep
#  action:
#    - service: switch.turn_off
#      entity_id: switchlinc_relay_dual_band_30_cd_2c
#    - service: input_boolean.turn_off
#      entity_id: input_boolean.whfan_sleep_timer
