- alias: Livingroom Motion On
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: light.switchlinc_dimmer_16_26_6e
      state: 'off'
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  action:
    - service: light.turn_on
      entity_id: light.switchlinc_dimmer_16_26_6e
    - service: input_boolean.turn_on
      entity_id: input_boolean.livingroom_auto_on

- alias: Livingroom Motion Off
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binabinary_sensor.livingroom_motion_sensor
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.livingroom_auto_on
      state: 'on'
    - condition: state
      entity_id: light.switchlinc_dimmer_16_26_6e
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.switchlinc_dimmer_16_26_6e

- alias: Living Room Turned Off
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: light.switchlinc_dimmer_16_26_6e
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.livingroom_auto_on
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.livingroom_auto_on

- alias: Garage Lights Motion
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.garage_lights
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.garage_lights
    - service: input_boolean.turn_on
      entity_id: input_boolean.garage_auto_on

- alias: Garage Lights Motion Off
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_motion
      to: 'off'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: input_boolean.garage_auto_on
      state: 'on'
    - condition: state
      entity_id: switch.garage_lights
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.garage_lights
    - service: input_boolean.turn_off
      entity_id: input_boolean.garage_auto_on

- alias: Garage Lights Turned Off
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: switch.garage_lights
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.garage_auto_on
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: inpout_boolean.garage_auto_on
