- alias: Christmas Lights On
  id: christmas_lights_on
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  action:
    service: light.turn_on
    entity_id: light.keypadlinc_dimmer_16_79_b8_main

- alias: Christmas Lights Off
  id: christmas_lights_off
  initial_state: true
  trigger:
    platform: time
    at: "22:00:00"
  action:
    service: light.turn_off
    entity_id: light.keypadlinc_dimmer_16_79_b8_main

- alias: Christmas Tree Lights Off
  id: christmas_tree_lights_off
  initial_state: true
  trigger:
    platform: time
    at: "22:30:00"
  action:
    service: switch.turn_off
    entity_id: switch.christmas_lights_2

- alias: Christmas Tree Lights On
  id: christmas_tree_lights_on
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  action:
    service: switch.turn_on
    entity_id: switch.christmas_lights_2
