- alias: Office Speaker Volume 8
  id: 'set_office_speaker_volume'
  initial_state: false
  trigger:
    platform: time
    at: "08:00:00"
  action:
    service: media_player.volume_set
    data:
      entity_id: media_player.office_speaker
      volume_level: '0.8'

- alias: Office Speaker Volume 2
  id: 'set_office_speaker_volume'
  initial_state: false
  trigger:
    platform: time
    at: "19:00:00"
  action:
    service: media_player.volume_set
    data:
      entity_id: media_player.office_speaker
      volume_level: '0.2'

- alias: Morning Routine Reminder
  id: 'kids_shoes_on_reminder'
  initial_state: false
  trigger:
    platform: time
    at: "07:40:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.whole_house_speakers
        volume_level: '0.9'
    - service: tts.google_translate_say
      entity_id: media_player.whole_house_speakers
      data_template:
        message: "May I have your attention please.  May I have your attention Please.  Its time to put on socks and shoes and head to school.  I repeat,  its time to put on socks and shoes and head to school."
        cache: false

- alias: Morning Hi-5
  id: 'kids_hi-five_reminder'
  initial_state: true
  trigger:
    platform: time
    at: "06:45:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.whole_house_speakers
        volume_level: '0.9'
    - service: tts.google_translate_say
      entity_id: media_player.whole_house_speakers
      data_template:
        message: "May I have your attention please.  May I have your attention Please.  Its time to start your Morning High 5.  I repeat, its time to start your Morning High 5."
        cache: false
