- alias: Activate WHF Sleep
  initial_state: "off"
  trigger:
    - platform: state
      entity_id: input_boolean.whfan_sleep_timer
      to: 'on'
  #condition:
  #  - condition: state
      #entity_id: switch.switchlinc_relay_dual_band_30_cd_2c
      #state: 'on'
  action:
      service: timer.start
      entity_id: whfsleep

#- alias: Turn off WHFan
#  id: 'turn_off_whole_house_fan'
#  initial_state: "on"
#  trigger:
#    - platform: event
#      event_type: timer.finished
#      event_data:
#        entity_id: timer.whfsleep
#  action:
#    - service: switch.turn_off
#      entity_id: switchlinc_relay_dual_band_30_cd_2c
#    - service: input_boolean.turn_off
#      entity_id: input_boolean.whfan_sleep_timer
