- alias: Alarm Off
  id: 'alarm-off'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.red_button
    to: 'on'
  action:
    - service: automation.turn_off
      entity_id: group.alarm_system
    #
    #   entity_id: automation.garage_man_door_alarm
    # - service: automation.turn_off
    #   entity_id: automation.living_motion_alarm
    # - service: automation.turn_off
    #   entity_id: automation.living_room_motion_alarm
    # - service: automation.turn_off
    #   entity_id: automation.luke_door_alarm

- alias: Alarm On
  id: 'alarm-on'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.green_button
    to: 'on'
  #condition:
  #  condition: state
  #  entity_id: group.all_devices
  #  state: 'home'
  action:
    - service: automation.turn_on
      entity_id: group.alarm_system
    - service: light.turn_off
      entity_id: light.lamplinc_dimmer_3a_b1_e7
      transition: 60
    - service: light.turn_off
      entity_id: light.monitor_leds
      transition: 10
      flash: short
    #
    #   entity_id: automation.garage_man_door_alarm
    # - service: automation.turn_on
    #   entity_id: automation.living_motion_alarm
    # - service: automation.turn_on
    #   entity_id: automation.living_room_motion_alarm
    # - service: automation.turn_on
    #   entity_id: automation.luke_door_alarm
