- alias: Alarm
  id: 'alarm'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.red_button
    to: 'on'
  action:
    - service: automation.toggle
      entity_id: group.alarm_system
    #
    #   entity_id: automation.garage_man_door_alarm
    # - service: automation.turn_off
    #   entity_id: automation.living_motion_alarm
    # - service: automation.turn_off
    #   entity_id: automation.living_room_motion_alarm
    # - service: automation.turn_off
    #   entity_id: automation.luke_door_alarm

- alias: NightstandButton
  id: 'nightstandbutton'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.nightstand_button
    to: 'on'
  action:
    - service: light.toggle
      entity_id: light.lamplinc_dimmer_3a_b3_2f

- alias: Desk Lights
  id: 'desk-lights'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.green_button
    to: 'on'
  #condition:
  #  condition: state
  #  entity_id: group.all_devices
  #  state: 'home'
  action:
    - service: light.toggle
      entity_id: light.lamplinc_dimmer_3a_b1_e7
      #transition: 10
    - service: light.toggle
      entity_id: light.monitor_leds
      #color_temp: 2700
      #transition: 10
      #flash: short
    #
    #   entity_id: automation.garage_man_door_alarm
    # - service: automation.turn_on
    #   entity_id: automation.living_motion_alarm
    # - service: automation.turn_on
    #   entity_id: automation.living_room_motion_alarm
    # - service: automation.turn_on
    #   entity_id: automation.luke_door_alarm

- alias: Monitor Blue
  id: 'leds-blue'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.remote_button_1
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.monitor_leds
      color_name: blue

- alias: Monitor Red
  id: 'leds-red'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.remote_button_2
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.monitor_leds
      color_name: red

- alias: Monitor Blue
  id: 'leds-blue'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.remote_button_1
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.monitor_leds

- alias: Monitor Red
  id: 'leds-red'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.remote_button_2
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.monitor_leds
