# Motion detector - study lights
- alias: Living Room Motion Alarm
  id: 'living_motion_alarm'
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.family_room_motion
    to: 'on'
  action:
    - service: notify.simplepush
      data:
        title: Security Alert
        message: Motion Detected in Living Room!

- alias: Garage Man Door Alarm
  id: 'garage_man_alarm'
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.garage_man_door
    to: 'on'
  action:
    - service: notify.simplepush
      data:
        title: Security Alert
        message: Garage Man Door Opened!

- alias: Luke Door Alarm
  id: 'luke_door_alarm'
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.luke_s_bedroom_door
    #to: 'on'
  action:
    - service: notify.simplepush
      data:
        title: Security Alert
        message: Luke's Bedroom Door Opened!

- alias: Tablet Cabinet Alarm
  id: 'tab_cab_alarm'
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.tablet_cabinet
    to: 'on'
  action:
    - service: notify.simplepush
      data:
        title: Security Alert
        message: Tablet Cabinet Opened!
