- id: '00004721003'
  alias: Two Minute Warning Spiel
  trigger:
      platform: state
      entity_id: binary_sensor.garage_man_door
  action:
      service: tts.google_translate_say
      #entity_id: media_player.googlehomehub7838
      entity_id: media_player.whole_house_speakers
      data_template:
        message: "Attention!  This is your two Minute Warning!"
        cache: false

#Automations to handle the PIR sensor to control the Room light.
- id: '00004711005'
  alias: Luke Night Light off at 1030
  trigger:
    platform: time
    at: "22:30:00"
  action:
    service: switch.turn_off
    entity_id:  switch.christmas_lights

- id: '00004711006'
  alias: Luke Night Light on at 1800
  trigger:
    platform: time
    at: "18:00:00"
  action:
    service: switch.turn_on
    entity_id:  switch.christmas_lights

- id: '00004711006'
  alias: Bedtime Reminder
  trigger:
    platform: time
    at: "23:00:00"
  condition:
    condition: state
    entity_id: light.monitor_leds
    state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.monitor_leds
      color_name: green
      brightness: 255
      flash: long
