# Motion detector - study lights
- alias: Living Room Motion Alarm
  id: 'living_motion_alarm'
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.wyzesense_779d4464
    to: 'on'
  action:
    - service: notify.simplepush
      data:
        title: Security Alert
        message: Motion Detected in Living Room!

- alias: Garage Man Door Alarm
  id: 'garage_man_alarm'
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.garage_man_door
    to: 'on'
  action:
    - service: notify.simplepush
      data:
        title: Security Alert
        message: Garage Man Door Opened!

- alias: Luke Door Alarm
  id: 'luke_door_alarm'
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.wyzesense_779c28b9
    to: 'on'
  action:
    - service: notify.simplepush
      data:
        title: Security Alert
        message: Luke's Bedroom Door Opened!

- alias: Joel & Emily's Door Alarm
  id: 'joel_emily_door_alarm'
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.wyzesense_779be395
    to: 'on'
  action:
    - service: notify.simplepush
      data:
        title: Security Alert
        message: Joel & Emily's Bedroom Door Opened!

#- alias: Front Door Alarm
#  id: 'front_door_alarm'
#  initial_state: false
#  trigger:
#    platform: state
#    entity_id: binary_sensor.wyzesense_779be342
#    to: 'on'
#  action:
#    - service: notify.simplepush
#      data:
#        title: Security Alert
#        message: Front Door Opened!

- alias: Door Alarm
  id: 'door_alarm'
  initial_state: false
  trigger:
    - platform: state
      entity_id: binary_sensor.wyzesense_779be342
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wyzesense_779c28b9
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wyzesense_779c28a0
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wyzesense_779be395
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_side_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_man_door
      to: 'on'
  action:
    - service: notify.simplepush
      data:
        title: Security Alert
        #message: Sensor {{ trigger.to_state.attributes.friendly_name }} activated!
        #message: "The {{ trigger.to_state.attributes.friendly_name }} sensor has TRIGGERED!!!"
        message: "Door sensor has been TRIGGERED!!!"

    #- alias: Hallway Motion
#  id: 'hallway_motion_alarm'
#  initial_state: false
#  trigger:
#    platform: state
#    entity_id: binary_sensor.wyzesense_7798e926
#    to: 'on'
#  action:
#    - service: notify.simplepush
#      data:
#        title: Security Alert
#        message: Motion detected in Hallway

- alias: Motion Alarm
  id: 'motion_alarm'
  initial_state: false
  trigger:
    - platform: state
      entity_id: binary_sensor.wyzesense_7798e926
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wyzesense_779d4464
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wyzesense_779d5d80
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wyzesense_77a5e9bd
      to: 'on'
  action:
    - service: notify.simplepush
      data:
        title: Security Alert
        #message: 'Sensor {{ trigger.to_state.attributes.friendly_name }} activated!'
        message: 'Motion sensor has been TRIGGERED!!!'
        #message: "The {{ trigger.to_state.attributes.friendly_name }} sensor has TRIGGERED!!!"
    - service: light.turn_on
      data:
        entity_id: light.desk_indicator_light
        effect: 'Stage 2'
    - delay:
        minutes: 1
    - service: light.turn_off
      entity_id: light.desk_indicator_light

- alias: Notifier Test
  id: 'notifier_test'
  initial_state: false
  trigger:
    - platform: state
      entity_id: binary_sensor.wyzesense_7798e926
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.desk_indicator_light
        #effect: 'Stage 2'
    - delay:
        minutes: 1
    - service: light.turn_off
      entity_id: light.desk_indicator_light
