- alias: Entertainment Center on at 8AM
  initial_state: "on"
  trigger:
    platform: time
    at: "08:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: switch.turn_on
    entity_id:  switch.entertainment_center

- alias: Entertainment Center on at 5AM
  initial_state: "on"
  trigger:
    platform: time
    at: "05:00:00"
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: switch.turn_on
    entity_id:  switch.entertainment_center

- alias: Entertainment Center on at 5AM for No School Days
  initial_state: "on"
  trigger:
    platform: time
    at: "05:00:00"
  condition:
    - condition: state
      entity_id: calendar.no_school_days
      state: 'on'
  action:
    service: switch.turn_on
    entity_id:  switch.entertainment_center

- alias: Porch Lights on at Sunset
  initial_state: "on"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:05:00"
  action:
    service: switch.turn_on
    entity_id: switch.keypadlinc_on_off_22_cd_f9_main

- alias: Porch Lights off at 9:30 PM
  initial_state: "on"
  trigger:
    platform: time
    at: "21:30:00"
  action:
    service: switch.turn_off
    entity_id: switch.keypadlinc_on_off_22_cd_f9_main

- alias: Entertainment Center off at 0430
  initial_state: "on"
  trigger:
    platform: time
    at: "04:00:00"
  action:
      service: switch.turn_off
      entity_id:  switch.entertainment_center
