#- id: '58888675312'
- alias: Entertainment Center on at 8AM
  trigger:
    platform: time
    at: "08:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: switch.turn_on
    entity_id:  switch.entertainment_center
